"""Static target/domain audit; no native simulations or sealed scientific arrays."""
import math,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'src'))
from bt_history.contracts import digest,file_hash,verify_sources
from bt_history.data_control import read_json,write_json
root=Path(__file__).resolve().parents[1];c=read_json(root/'contracts/science_contract.json');selected=read_json(root/'contracts/selected_native_contract.json');verify_sources(c)
tables=Path(c['native_python_root'])/'py21cmfast/_data'
selected['physics_table_sha256']={str(p):file_hash(p) for p in sorted(tables.iterdir()) if p.is_file()};selected['physics_table_fingerprint']=digest(selected['physics_table_sha256'])
write_json(root/'contracts/selected_native_contract.json',selected)
b=read_json(root/'configs/data_stage_budgets.json');b['selected_native_contract_sha256']=file_hash(root/'contracts/selected_native_contract.json');write_json(root/'configs/data_stage_budgets.json',b)
u=c['simulation_settings']['user_params'];h=c['cosmology']['hlittle'];L=u['BOX_LEN']
r={'status':'STATIC_AUDITED_RUNTIME_BLOCKED','original_source_native_observation_hashes_unchanged':True,'source_fingerprint':selected['source_fingerprint'],'physics_table_fingerprint':selected['physics_table_fingerprint'],'native_sha256':selected['native_sha256'],'native_confirmed':False,'source_evidence':{'seed_argument':'src/21cmFAST.h:149 unsigned long long; outputs.py:174 passthrough; GenerateICs.c:126 gsl_rng_set, :142 thread RNG splitting','PL_formula':'src/ps.c:394-395 dsigma_dk, :571-572 power_in_k; MS=POWER_INDEX removes KP break','variance_cutoff':'src/ps.c:421-465 sigma_z0: k from 1e-99/R to 350/R in mode6','normalization':'src/ps.c:635-674 init_ps: R8=8/h, same dsigma integrand and sigma8 normalization','HMF':'src/ps.c:874 and following sigma_z0 calls; ComputeLF initialises PS/source tables'},'grid_geometry':{'box_Mpc':L,'fundamental_1_Mpc':2*math.pi/L,'DIM_axis_Nyquist_1_Mpc':math.pi*u['DIM']/L,'HII_DIM_axis_Nyquist_1_Mpc':math.pi*u['HII_DIM']/L,'DIM_axis_Nyquist_h_Mpc':math.pi*u['DIM']/L/h,'HII_DIM_axis_Nyquist_h_Mpc':math.pi*u['HII_DIM']/L/h,'KP_native_range_1_Mpc':[1*h,30*h],'sigma8_integral_kmax_1_Mpc':350/(8/h)},'risk_status':{'PL_KP_invariance':'algebraic expectation; native measurement not executed','high_MS':'finite mass-dependent integration cutoffs; convergence/overflow/GSL behavior unqualified, no proven safe subdomain','KP_above_field_Nyquist':'cannot infer no source/HMF effect; sigma integrals not bounded by field FFT Nyquist','z35_early_ionization':'screening warning if 1-xHI>.01; not yet measured','z5_neutral_extension':'screening warning if xHI>.01; not yet measured','32_output_nodes':'not all internal evolution nodes; current target only, no redshift convergence claim'},'requested_seed':725213656658,'effective_seed':'pending real returned-object verification; no manual modulo','thread_count_frozen':16,'legacy_quarantined_records':45,'legacy_transferred':0,'sealed_test_labels_read':False,'new_labels_generated':0,'existing448_sha256':file_hash(root/'configs/proposed_448_point_design.json'),'manifest_storage_bytes':sum(p.stat().st_size for p in (root/'manifests').glob('*') if p.is_file()),'new_label_storage_bytes':0}
write_json(root/'results/data_provenance_audit.json',r)
