"""Write unapproved resource proposals and predeclared QA, never grant execution."""
import json,sys
from pathlib import Path
sys.path.insert(0,str(Path(__file__).resolve().parents[1]/'src'))
from bt_history.contracts import digest,file_hash
from bt_history.data_control import read_json,write_json
root=Path(__file__).resolve().parents[1];c=read_json(root/'contracts/science_contract.json');d=read_json(root/'contracts/dataset_design.json')
if (root/'contracts/selected_native_contract.json').exists():raise FileExistsError('Existing data contracts must not be overwritten; create a reviewed version instead')
native=next(p for p,h in c['source_and_native_fingerprints'].items() if h==c['native_sha256'] and p.endswith('.so'))
source={p:h for p,h in c['source_and_native_fingerprints'].items() if not p.endswith('.so')}
selected={'status':'CANDIDATE_NOT_CONFIRMED','confirmed':False,'approval_reference':None,'native_sha256':c['native_sha256'],'native_path':native,'python_package_root':c['native_python_root'],'source_fingerprint':digest(source),'source_files':source,'science_contract_hash':digest(c),'config_hash':digest(c),'postprocessing_hash':next(h for p,h in source.items() if p.endswith('/non21_likelihood.py')),'old_audit_native_sha256':'80b30c5c5c4bb32949db8664e852054c43a73e7ac6ac397f57925ea0f89bad9c','old_native_training_eligible':False,'compatible_runtime_approved':False,'runtime_approval_reference':None,'allowed_runtime_fingerprints':[],'approval_required_fields':['confirmed','approval_reference','compatible_runtime_approved','runtime_approval_reference','allowed_runtime_fingerprints']}
write_json(root/'contracts/selected_native_contract.json',selected)
write_json(root/'contracts/split_policy.json',{'version':d['design_version'],'design_sha256':file_hash(root/'contracts/dataset_design.json'),'counts':{'train':4096,'validation':512,'sealed_test':1024,'preflight':12,'challenge_development':24},'frozen':True,'old_448':'train only, preserved exact IDs/coordinates','grouping':'physical tuple and explicit PL/perturbation family; NOT shared IC seed','all_IC_extensions_same_family':True,'future_refinement':'new train-only design version; existing validation/test unchanged','duplicate_rounding':'12 decimals in prior-normalized coordinates','same_point_repeats':'preflight only; not independent samples','resampling_failed_points':False,'test_backups':{'enabled':False,'original_denominator':1024,'max_infrastructure_retries_proposal':1,'numerical_retries':0,'backups_if_later_authorized':'separate prespecified supplementary sample, never replaces original denominator'},'legacy_random_split_allowed_for_v1':False})
write_json(root/'contracts/data_quality_protocol.json',{'version':'v1','status':'PREDECLARED_ENGINEERING_QA','label':'global_xHI only','grid':'exact array equality, strictly increasing, no resampling','range':{'qualified_min':0.,'qualified_max':1.,'tiny_excursion_tolerance':1e-6,'tiny_excursion_action':'quarantine raw values with flag; never clip','larger_excursion_action':'numerical failure retaining raw result'},'native_same_path_parity':'bitwise equality for history, tau inputs/output, observed xHI, LF and each likelihood component','tolerance_relaxation':'none; first assess predeclared original-repeat variation, then investigate','saved_derived_parity':{'tau_absolute_tolerance':1e-8,'observed_xHI_absolute_tolerance':1e-10,'recompute_with_original':True},'endpoint_warnings':{'z35_ionized_fraction_gt':.01,'z5_neutral_fraction_gt':.01,'classification':'science_domain_warning, retain valid sample','meaning':'screening flags, not scientific precision gates'},'failure_classes':['runtime_native_load_failure','infrastructure_failure','timeout','out_of_memory','numerical_failure','schema_provenance_failure','science_domain_warning','success'],'seed':{'requested':725213656658,'native_argument':'unsigned long long','python_pass_through':True,'manual_modulo_forbidden':True,'returned_effective_seed_required':True,'GSL_rng_note':'GSL mt19937 seeds thread RNGs; preserve implementation and thread count; not an ensemble-IC target'},'cache':'regenerate=True write=False; no cross-parameter reuse','mechanical_test_QA':'same fixed rules within isolated sealing worker; no scientific numbers in public receipts','debug_products':'none retained by default; all temporary stdout/stderr private and encrypted for sealed workers'})
write_json(root/'contracts/sealed_test_policy.json',{'generation_authorized':False,'generation_approval_reference':None,'read_authorized':False,'read_approval_reference':None,'parameter_design_access':True,'design':'manifests/sealed_test_design.jsonl','original_denominator':1024,'label_count':0,'model_freeze_record':'artifacts/scientific_model_freeze.json','public_key_file':None,'public_key_fingerprint':None,'encryption':'GnuPG public-key encryption; private key must be held outside this project/development runtime','storage':'sealed_store; ciphertext labels plus encrypted native logs; mode 0700 temporary plaintext removed at worker exit','public_receipt_fields':['sample_id','attempt_id','split','simulation_status','exit_code','ciphertext_sha256','ciphertext_bytes','wall_seconds','allocation_core_hours'],'developer_loader':'reject sealed split/path/extensions before label reads; no automatic glob','early_generation':False,'unseal_event_log':'results/unseal_events.jsonl','no_unseal_implementation_this_round':True,'known_limit':'filesystem mode alone does not isolate same-UID access; require external key holder and approved runtime isolation before generation'})
manifest_names={'preflight':['preflight'],'train':['train_initial_448','train_full_design'],'validation':['validation_design'],'challenge_development':['challenge_development'],'sealed_test':['sealed_test_design']}
proposed={'preflight':12,'train':4096,'validation':512,'challenge_development':24,'sealed_test':1024}
b={'authorized':False,'approval_reference':None,'max_evaluations':0,'science_contract_hash':digest(c),'dataset_design_sha256':file_hash(root/'contracts/dataset_design.json'),'selected_native_contract_sha256':file_hash(root/'contracts/selected_native_contract.json'),'allowed_partition':None,'allowed_account':None,'max_concurrent_tasks':0,'stages':{}}
for stage,n in proposed.items():
    b['stages'][stage]={'authorized':False,'max_attempts':0,'max_retry_attempts':0,'max_retries_per_sample':0,'max_reserved_core_hours':0,'cpus':16,'memory_MiB':16384,'wall_seconds':7200,'max_concurrent':0,'manifests':['manifests/'+x+'.jsonl' for x in manifest_names[stage]],'proposed_unique_or_evaluation_count':n,'proposal_not_authorization':True}
write_json(root/'configs/data_stage_budgets.json',b)
write_json(root/'results/resource_estimate.json',{'status':'UNMEASURED_NEW_NATIVE_DOMAIN','authorized_attempts':0,'actual_new_attempts':0,'actual_new_allocation_core_hours':0,'planned_counts':proposed,'allowed_retries':0,'proposal_allocation':{'cpus':16,'memory_MiB':16384,'wall_cap_seconds':7200,'initial_concurrency_proposal':1},'old_local_timing_is_not_new_domain_cost':True,'capacity_ceiling_if_2h_each_not_a_forecast':{k:n*16*2 for k,n in proposed.items()},'post_preflight_budget_method':'sum measured allocated CPU*elapsed per attempted point + charged retry/timeout/OOM costs; report separate strata and allocation ceilings','storage':{'raw_history_float64_bytes_per_success':512,'raw_history_5632_samples_bytes':5632*512,'metadata_ciphertext_logs_bytes':'not measured','temporary_field_storage':'not measured; no persistent field cache; approved scratch capacity required'},'cost_measurements_required':['typical','strong_BT','PL','peak_RSS','CPU_utilization','temporary/output_bytes','timeouts','numerical_failures']})
write_json(root/'results/native_parity.json',{'status':'BLOCKED','passed':False,'science_contract_hash':digest(c),'reason':'native selection/runtime and nonzero preflight budget unconfirmed','attempted_full_evaluations':0})
write_json(root/'results/pl_limit_checks.json',{'status':'STATIC_AUDIT_ONLY','PL_limit_MS':.968,'static_algebraic_cancellation':True,'native_power_variance_measured':False,'native_history_passed':False,'science_contract_hash':digest(c),'reason':'compatible confirmed runtime and budget required; no unqualified KP dependence learned'})
