import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
def w(name,value):
    p=root/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(value,indent=2)+'\n')
arch={'width':256,'hidden':512,'blocks':4,'residual_scale':.5}
w('contracts/architecture_contract.json',{'architecture':'PreNorm ResMLP','architecture_args':arch,'activation':'SiLU','initialization':'Xavier uniform Linear, zero biases','normalization':'train-only coordinate standardization; stored log10 stays unchanged','output':'global_xHI only','direct_decoder':'sigmoid','tau_heads':False,'candidate_seeds':[11,29,47,71,101],'residual_gate':'disabled: PL mismatches','PCA_gate':'disabled pending train-fit physical/likelihood reconstruction','shape_constraints':None,'selection_budget':'one registered direct configuration, five seeds; residual only after compatibility gate; no unbounded tuning'})
w('configs/training.json',{'seeds':[11,29,47,71,101],'architecture':arch,'optimizer':'AdamW','learning_rate':.001,'weight_decay':.0001,'batch_size':128,'epochs':1000,'scheduler':'ReduceLROnPlateau factor 0.5','scheduler_patience':20,'early_stopping_patience':60,'gradient_clip':1.,'threads':1,'minimum_train_groups':100,'minimum_validation_groups':25,'loss':'mean squared physical global_xHI error','redshift_weights':'uniform','selection':'minimum validation history MSE','minimum_counts_note':'Execution guard only, not scientific sufficiency or success threshold'})
w('configs/direct_resmlp.json',{'decoder':'direct','enabled':True,'production_accepted':False,'architecture':arch})
w('configs/residual_resmlp.json',{'decoder':'PL_logit_residual','enabled':False,'epsilon':1e-5,'compatibility_passed':False,'PCA_enabled':False,'reason':'cosmology/PHOTON_CONS/redshift/IC mismatch unresolved'})
w('contracts/data_contract.json',{'label':'volume-mean global_xHI, full 32-node trajectory','ground_truth':'contract-matched local BT native only','source_access':'explicit development allowlist, immutable external paths; no sealed-label reads','required_fields':['sample_id','physical_parameters','fixed_parameters','ic_seed','redshifts','global_xHI','exact_tau','exact_xHI_at_observation_redshifts','simulation_status','science_contract_hash','source_native_config_hashes','provenance'],'validation':{'finite':True,'strict_grid':True,'physical_range':[0,1],'imputation':False,'label_clipping':False,'tau_absolute_tolerance':1e-8,'xHI_obs_absolute_tolerance':1e-10},'split':'group on complete physical parameter tuple, all IC together; 80/20 train/development-validation','normalization_and_PCA':'train only','seed_target':'fixed_ic','failure_records':'retain parameters, reason and stratum; no implicit -infinity prior','sealed_test':'not opened; separate authorization required','legacy_84_node_data':'ineligible: different IC/grid/physics definition'})
thresholds={'trajectory_RMSE_q95_max':.01,'trajectory_max_abs_q95_max':.03,'tau_abs_q90_max':.001,'tau_abs_mean_bias_max':.0002,'xHI_obs_abs_q90_max':.01,'delta_logL_tau_abs_q90_max':.1,'delta_logL_xHI_abs_q90_max':.1,'delta_logL_joint_abs_q90_max':.1}
w('contracts/acceptance_protocol.json',{'status':'PROPOSED_REQUIRES_SCIENTIFIC_CONFIRMATION','thresholds':thresholds,'provenance':'tau and joint q90, tau bias inherited as proposals from old history validation draft; history/xHI and separate likelihood proposals new; no retrospective relaxation','representation_budget_fraction':.2,'groups':['each target inference region separately','low xHI <=0.1','transition 0.1<xHI<0.9','high xHI>=0.9','exact 0 and 1','prior boundaries','penalized McGreer region'],'quantile_and_bootstrap_unit':'physical parameter trajectory, never individual redshift; stratify task region','bootstrap':{'resamples':2000,'seed':20260930,'confidence':.95},'ensemble':'five seeds; decode individually then arithmetic mean physical xHI','likelihood':'original split-normal tau and original neutral fraction; report both components and sum; LF unchanged','posterior':{'required':['independent exact location/width/correlation comparison','support overlap including spurious high probability regions','training coverage diagnostics'],'ESS_fraction_min_proposal':.5,'production_passed':False},'final_test':{'authorized':False,'must_freeze':['model','normalizer','split','PCA','thresholds','source/native','analysis code'],'no_online_updates':True},'end_to_end_timing':'includes exact LF, original tau/xHI postprocessing and likelihood; no speedup claim before measurement'})
w('configs/validation.json',{'protocol':'contracts/acceptance_protocol.json','sealed_test_enabled':False,'minimum_penalized_xHI_groups_proposal':25,'report_all_seeds':True,'report_ensemble':True})
w('configs/budget.json',{'authorized':False,'max_evaluations':0,'science_contract_hash':None,'design_sha256':None,'proposed_pilot_per_target':128,'resources_per_label':{'cpus':16,'memory_GiB':16,'wall_hours':2},'audit_local_cost_only':{'seconds_per_label':673.29,'core_hours_per_label':2.99,'256_labels_core_hours':766},'note':'Costs from five local old-native points; broad prior and repaired version may differ. No automatic submission.'})
for path in ['results/split_manifests','results/reconstruction_metrics','results/training_curves','results/per_seed_metrics','results/ensemble_metrics','results/likelihood_error_metrics','results/timing_and_resource_metrics','artifacts/checkpoints','artifacts/normalizers','artifacts/optional_pca_basis']:
    w(path+'/status.json',{'status':'pending_scientific_data_and_gates','synthetic_is_scientific_evidence':False})
w('artifacts/model_manifest.json',{'status':'NO_TRAINED_ACCEPTED_MODEL','production_accepted':False,'sealed_test_opened':False,'posterior_passed':False})
